---
title: "EASE"
author: "Kate Mills"
date: "10/18/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```

Load required packages and scripts (no input needed)
```{r setup, include=FALSE}
packages <- c( "tidyverse","ggmap")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))
}
lapply(packages, library, character.only = TRUE)

# Kate's custom theme
theme_kate <- function () { 
    theme_bw() +
  theme_minimal(base_size = 14, base_family = "Avenir") +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        legend.position="bottom")
}

workdir=as.character(read.table((paste0(getwd(),"/org/workdir.txt")))[[1]])
```

Geolocation data
```{r}
# Generate list of subs
subs<-list.files(path = paste0(workdir,"Data_Winter2017/"))

# Remove sub 21 because of some error in reading data & final entry
subs<-subs[-21]
subs<-subs[-23]

# Extract geolocation data
extract_geo=function(sub){
  files<-list.files(path=paste0(workdir,"Data_Winter2017/",sub,"/"),pattern = "log.decrypted")
  output<-lapply(X = files,FUN = function(file){
    if (nchar(read.csv(paste0(workdir,"Data_Winter2017/",sub,"/",file),
                       header = FALSE,sep = " ",stringsAsFactors = FALSE)$V5[[1]])>11){
      geooutput<-read.csv(paste0(workdir,"Data_Winter2017/",sub,"/",file),
                          header = FALSE,
                          sep = " ",
                          col.names = paste0("V",seq_len(200)),
                          stringsAsFactors = FALSE,
                          fill = TRUE) %>%
        select(V1,V2,V4,V5,V7) %>%
        mutate(startdate=substring(V1,3,last=nchar(V1)),
               starttime=substring(V2,1,last=(nchar(V2)-1)),
               enddate=substring(V4,2,last=nchar(V4)),
               endtime=substring(V5,1,last=8),
               lat=substring(V5,first=12,last=nchar(V5)),
               lon=substring(V7,first=1,last=(nchar(V7)-1))) %>%
        select(-contains("V"))
      geooutput
    }
  })
  output.df<-data.table::rbindlist(output, fill=TRUE)
  output.df
  if (nrow(output.df)>0){cbind(sub,output.df)
  } else {
    output<-cbind(sub,NA,NA,NA,NA,NA,NA)
    colnames(output)<-c("sub","startdate","starttime","enddate","endtime","lat","lon")
    output.df<-as.data.frame(output)
    output.df
  }
}
extract_geo_out<-lapply(subs,extract_geo)
extract_geo_out.df<-data.table::rbindlist(extract_geo_out) %>%
  na.omit(.) %>%
  mutate(lon=as.numeric(as.character(lon)),
         lat=as.numeric(as.character(lat))) %>%
  filter(!lat==0,!lon==0) 

write.csv(extract_geo_out.df,file = paste0(workdir,"Processed_Data_KLM/Geo/data/geo_data.csv"))
print(paste0("There are ",length(unique(extract_geo_out.df$sub))," EASE participants with geolocation data"))
```

Analyzing geolocation data
```{r}

```

Plotting geolocation data
```{r}
resave_graphs=FALSE

# first test of making maps
testmap<- get_map(location = "Eugene", zoom = 14,
                  maptype = "roadmap", scale = 2)
groupheat<-ggmap(testmap) +
  geom_point(data = (extract_geo_out.df %>%
                       select(lon,lat,sub)),
             aes(x = lon, y = lat,
                 colour = sub,
                 alpha = 1),
             size=3) + 
  # geom_path(data = (extract_geo_out.df %>%
  #                      select(lon,lat,sub)),
  #           aes(colour=sub),
  #           size = .5,
  #           lineend = "round") + 
  stat_density2d(aes(x = lon, y = lat, 
                     fill = ..level.. , alpha = ..level..), bins = 100, 
                 data = (extract_geo_out.df %>%
                       select(lon,lat,sub)), geom = 'polygon') +
#  scale_alpha(range = c(.4, .7), guide = FALSE) +
  guides(fill = guide_colorbar(barwidth = 1.5, barheight = 10)) +
  theme(legend.position="none")

if(resave_graphs){ggsave(filename=paste0(workdir,"Processed_Data_KLM/Geo/graphs/groupheat_nolines.png"),
       plot=groupheat, width=6, height=5, units='in', dpi=300)}

```

Text data
```{r}
# Generate list of subs
subs<-list.files(path = paste0(workdir,"Data_Fall2016/"))

# Extract text data
extract_txt=function(sub){
  files<-list.files(path=paste0(workdir,"Data_Fall2016/",sub,"/"),pattern = "log.decrypted")
  output<-lapply(X = files,FUN = function(textfile){
    textoutput<-read.csv(paste0(workdir,"Data_Fall2016/",sub,"/",textfile),
                         header = FALSE,sep = " ",stringsAsFactors = FALSE)
    textoutput})
  output.df<-data.table::rbindlist(output, fill=TRUE)
  cbind(sub,output.df)
}
extract_txt_out<-lapply(subs,extract_txt)
extract_txt_out.df<-as.data.frame(do.call(rbind,extract_txt_out))
```