---
title: "geolocation"
author: "Kate Mills"
date: "10/18/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```

Load required packages and scripts (no input needed)
```{r setup, include=FALSE}
packages <- c( "tidyverse","ggmap","geosphere","lubridate","Imap","modeest")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))
}
lapply(packages, library, character.only = TRUE)

# Kate's custom theme
theme_kate <- function () { 
    theme_bw() +
  theme_minimal(base_size = 14, base_family = "Avenir") +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        legend.position="none")
}

workdir=as.character(read.table((paste0(getwd(),"/org/workdir.txt")))[[1]])
```

Extracting geolocation data from decryppted files
```{r}
# Participant ID to device ID
pidsid<-read.csv(paste0(workdir,"raw_data/demographics_ids/pid_sid.csv"),header = T,stringsAsFactors = F) %>%
  mutate(pid=gsub("[^0-9]", "",pid))

# Generate list of subs
subs<-bind_rows((as.data.frame(list.files(path = paste0(workdir,"raw_data/keyboard/keyboard_logs_fall2016/"))) %>% 
                   mutate(sid=.[[1]]))[-1],
                (as.data.frame(list.files(path = paste0(workdir,"raw_data/keyboard/keyboard_logs_winter2017/"))) %>% 
                   mutate(sid=.[[1]]))[-1]) %>%
  distinct(sid) %>%
  filter(!grepl(".py",sid))

# Extract text data
extract_geo=function(sid){
  if(file.exists(path=paste0(workdir,"raw_data/keyboard/keyboard_logs_fall2016/",sid,"/"))){
  files2016<-(as.data.frame(list.files(path=paste0(workdir,"raw_data/keyboard/keyboard_logs_fall2016/",sid,"/"),pattern = "log.decrypted")) %>%
                mutate(file=paste0(paste0(workdir,"raw_data/keyboard/keyboard_logs_fall2016/",sid,"/",.[[1]]))))}
  if(file.exists(path=paste0(workdir,"raw_data/keyboard/keyboard_logs_winter2017/",sid,"/"))){
    files2017<-(as.data.frame(list.files(path=paste0(workdir,"raw_data/keyboard/keyboard_logs_winter2017/",sid,"/"),pattern = "log.decrypted")) %>%
                mutate(file=paste0(workdir,"raw_data/keyboard/keyboard_logs_winter2017/",sid,"/",.[[1]])))}
  if(exists("files2016") & exists("files2017")) {
    files<-append(files2016$file,files2017$file)
  } else if(exists("files2016") & !exists("files2017")){
      files<-files2016$file
    } else if(exists("files2017")& !exists("files2016")){
      files<-files2017$file
    }
  rm(files2016,files2017)
  
  output<-lapply(X = files,FUN = function(file){
    if(nchar(read.csv(paste0(file),header = FALSE,sep = " ",stringsAsFactors = FALSE)$V5[[1]])>11){
      geooutput<-read.csv(file,
                          header = FALSE,
                          sep = " ",
                          col.names = paste0("V",seq_len(200)),
                          stringsAsFactors = FALSE,
                          fill = TRUE) %>%
        select(V1,V2,V4,V5,V7) %>%
        mutate(startdate=substring(V1,3,last=nchar(V1)),
               starttime=substring(V2,1,last=(nchar(V2)-1)),
               enddate=substring(V4,2,last=nchar(V4)),
               endtime=substring(V5,1,last=8),
               lat=substring(V5,first=12,last=nchar(V5)),
               lon=substring(V7,first=1,last=(nchar(V7)-1))) %>%
        select(-contains("V"))
      geooutput
    }
  })
  output.df<-data.table::rbindlist(output, fill=TRUE)
  output.df
  if (nrow(output.df)>0){cbind(sid,output.df)
  } else {
    output<-cbind(sid,NA,NA,NA,NA,NA,NA)
    colnames(output)<-c("sid","startdate","starttime","enddate","endtime","lat","lon")
    output.df<-as.data.frame(output)
    output.df
  }
}
extract_geo_out<-lapply(subs$sid[1],extract_geo)
extract_geo_out.df<-data.table::rbindlist(extract_geo_out) %>%
  na.omit(.) %>%
  mutate(lon=as.numeric(as.character(lon)),
         lat=as.numeric(as.character(lat))) %>%
  filter(!lat==0,!lon==0) 
             
write.csv(extract_geo_out.df,file = paste0(workdir,"output/processed_geolocation/geo_data.csv"),row.names = FALSE)
print(paste0("There are ",length(unique(extract_geo_out.df$pid))," EASE participants with geolocation data"))
```

Processing geolocation data
```{r}
geodata<-read.csv(file = paste0(workdir,"output/processed_geolocation/geo_data.csv"),header = TRUE,stringsAsFactors = FALSE)[2:8]

# Is the time point during the night or day?
# Is the time point a weekend or weekday?
geodata_classifytime<-geodata %>%
  mutate(timeofday=ifelse(hms(endtime)>hms(as.character("06:00:00")) &
                            hms(endtime)<hms(as.character("09:00:00")),"early morning",
                   ifelse(hms(endtime)>=hms(as.character("09:00:00")) &
                            hms(endtime)<hms(as.character("18:00:00")),"day",
                   ifelse(hms(endtime)>=hms(as.character("18:00:00")) &
                            hms(endtime)<=hms(as.character("23:00:00")),"evening",
                   ifelse(hms(endtime)<hms(as.character("06:00:00")) |
                            hms(endtime)>hms(as.character("23:00:00")),"night",NA))))) %>%
  mutate(day=wday(ymd(paste0(startdate)), label = TRUE)) %>%
  mutate(wkday=ifelse(day=="Sun" | day=="Sat",0,1))

# Calculate duration of measurement
geodata_duration<- geodata_classifytime %>%
  mutate(fullstart=ymd_hms(paste0(startdate," ",starttime)),
         fullstop=ymd_hms(paste0(enddate," ",endtime))) %>%
  mutate(duration=as.numeric((fullstop-fullstart),unit="secs"),
         diff=ifelse(sub == lag(sub),
                     as.numeric(fullstart - lag(fullstop),unit="secs"),NA)) %>%
  filter(!diff < 0) %>%
  mutate(diff=ifelse(sub == lag(sub),
                     as.numeric(fullstart - lag(fullstop),unit="secs"),NA),
         duration_period=seconds_to_period(duration)) %>%
  mutate(diff_period=seconds_to_period(diff))

# Calculate distance between time points
calc_distance=function(i){
  round(gdist(lon.1 = geodata_duration$lon[i], 
        lat.1 = geodata_duration$lat[i], 
        lon.2 = geodata_duration$lon[i+1], 
        lat.2 = geodata_duration$lat[i+1], 
        units="miles"),7)}
geodata_distance<-geodata_duration %>%
  mutate(distance=unlist(lag(lapply(calc_distance,X = 1:nrow(geodata_duration)))))  %>%
  mutate(distance=ifelse(is.na(diff),NA,distance))%>%
  mutate(diff_period=seconds_to_period(diff))

#write.csv(geodata_distance,file = paste0(workdir,"Processed_Data_KLM/Geo/data/geo_data_duration_distance.csv"))

# Calculate distance between present location and "home"
geodata_timeofday <-geodata_distance %>%
  group_by(sub,timeofday) %>%
  summarize(modelat=mlv(lat, method='mfv')[['M']],
            modelon=mlv(lon, method='mfv')[['M']]) %>%
  ungroup()

geodata_distance_home<-left_join(geodata_distance,
                                 (geodata_timeofday %>% 
                                    filter(timeofday=="night") %>%
                                    mutate(homelat=modelat,
                                           homelon=modelon) %>%
                                    select(sub,homelat,homelon)),
                                 by="sub")

calc_distance_home=function(i){
  round(gdist(lon.1 = geodata_distance_home$homelon[i], 
        lat.1 = geodata_distance_home$homelat[i], 
        lon.2 = geodata_distance_home$lon[i], 
        lat.2 = geodata_distance_home$lat[i], 
        units="miles"),7)}
geodata_distance_home<-geodata_distance_home %>%
  mutate(distfromhome=unlist(lapply(calc_distance_home,X = 1:nrow(geodata_distance_home)))) %>%
  mutate(home=ifelse(distfromhome<.02,1,0))

#write.csv(geodata_distance_home,file = paste0(workdir,"Processed_Data_KLM/Geo/data/geo_data_duration_distance.csv"))

# How much time is spent at home?
time_at_home<-geodata_distance_home %>%
  group_by(sub,home) %>%
  summarize(totaltime=sum(duration))%>%
  ungroup() %>%
  mutate(totaltime_period=seconds_to_period(as.numeric(totaltime)))

# How much data do we have per participant?
time_recording<-geodata_distance_home %>%
  group_by(sub) %>%
  summarize(totaltimerecording=sum(duration))%>%
  ungroup() %>%
  mutate(totaltime_period_recording=seconds_to_period(as.numeric(totaltimerecording)))

time_at_home<-left_join(time_at_home,time_recording,by="sub") %>%
  mutate(ratiotime=round(totaltime/totaltimerecording,3))%>%
  mutate(totaltime_period_recording=seconds_to_period(as.numeric(totaltimerecording)),
         totaltime_period=seconds_to_period(as.numeric(totaltime)))

#write.csv(time_at_home,file = paste0(workdir,"Processed_Data_KLM/Geo/data/time_at_home.csv"))

# Is this a stationary or transition period?

# Circadian movement

# 

```

Analyzing geolocation data
```{r}
geodata<-read.csv(file = paste0(workdir,"output/processed_geolocation/geo_data_duration_distance.csv"),header = TRUE,stringsAsFactors = FALSE)[2:8]

```

Plotting geolocation data
```{r}
resave_graphs=FALSE

geodata<-read.csv(file = paste0(workdir,"output/processed_geolocation/geo_data_duration_distance.csv"),header = TRUE,stringsAsFactors = FALSE)

# Plot movement across days for each participant
onthemove.plot<-ggplot(geodata %>% filter(!is.na(diff_period)),
                          aes(x=fullstop, y=distance, colour=sub)) + 
  geom_point(aes(colour=sub),size=1)+
  facet_grid(.~sub, scales='free',drop = TRUE) +
  labs(y="Distance from previous assessment point",
       x="Date/time")+
  theme_kate()+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 10, hjust = 1),
        strip.background = element_blank(),
        strip.text.x = element_blank())
onthemove.plot

onthemove.plot2<-ggplot(geodata_distance %>% filter(!is.na(diff_period)),
                          aes(x=fullstop, y=distance, colour=sub)) + 
  geom_point(aes(colour=sub),size=1)+
  facet_grid(.~sub, scales='free',drop = TRUE) +
  labs(y="Distance from previous assessment point",
       x="Date/time")+
  ylim(0,50) +
  theme_kate()+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 10, hjust = 1),
        strip.background = element_blank(),
        strip.text.x = element_blank())
onthemove.plot2

# QC time of day locations
qclocations<-ggmap(get_map(location = "Eugene", zoom = 14,
                  maptype = "roadmap", scale = 2)) +
  geom_point(data = geodata_timeofday,
             aes(x = modelon, y = modelat,
                 colour = timeofday),
             size=7) 
qclocations

# Plot timecourse of distance from home across the day/week
distfromhome.plot<-ggplot(geodata_distance_home %>% filter(!is.na(homelat)),
                          aes(x=fullstop, y=distfromhome,colour=sub)) + 
  geom_point(aes(colour=sub),size=1)+
  facet_grid(.~sub, scales='free',drop = TRUE) +
  labs(y="Distance from home (miles)",
       x="Date/time")+
  theme_kate()+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 10, hjust = 1),
        strip.background = element_blank(),
        strip.text.x = element_blank())
distfromhome.plot


# first test of making maps
testmap<- get_map(location = "Eugene", zoom = 14,
                  maptype = "roadmap", scale = 2)
groupheat<-ggmap(testmap) +
  geom_point(data = geodata,
             aes(x = lon, y = lat,
                 colour = sub,
                 alpha = 1),
             size=3) + 
   geom_path(data = (geodata %>%
                        select(lon,lat,sub)),
             aes(colour=sub),
             size = .5,
             lineend = "round") + 
  stat_density2d(aes(x = lon, y = lat, 
                     fill = ..level.. , alpha = ..level..), bins = 100, 
                 data = (geodata %>%
                       select(lon,lat,sub)), geom = 'polygon') +
#  scale_alpha(range = c(.4, .7), guide = FALSE) +
  guides(fill = guide_colorbar(barwidth = 1.5, barheight = 10)) +
  theme(legend.position="none")

if(resave_graphs){ggsave(filename=paste0(workdir,"output/summary_geolocation/graphs/groupheat_nolines_nopoints.png"),
       plot=groupheat, width=6, height=5, units='in', dpi=300)}

### Graph for Nick's presentation
testmap<- get_map(location = "Eugene", zoom = 14,
                  maptype = "roadmap", scale = 2)
personpath<-ggmap(testmap) +
  geom_point(data = geodata %>% 
               filter(sub==unique(geodata$sub)[4])%>%
                       mutate(lon=lon+.008,
                              lat=lat),
             aes(x = lon, y = lat,
                 alpha = 1),
             colour = "dodgerblue",
             size=3) + 
   geom_path(data = (geodata %>% 
                       filter(sub==unique(geodata$sub)[4])%>%
                        select(lon,lat,sub)%>%
                       mutate(lon=lon+.008,
                              lat=lat)),
             colour="dodgerblue",
             size = .7,
             lineend = "round") + 
  guides(fill = guide_colorbar(barwidth = 1.5, barheight = 10)) +
  theme(legend.position="none")

ggsave(filename=paste0(workdir,"output/summary_geolocation/graphs/individual_path.png"),plot=personpath, width=6, height=5, units='in', dpi=300)


```
